### ISSUE TITLE
react-scripts: command not found

### ISSUE THREAD

**Issue by talaniz** [allegro/hacktoberfest-dashboard#3]
- Cloned the project
- ran npm start per the README

**Output**
```
> hacktoberfest-monitor2@0.1.0 start /Users/talaniz/Workspace/hacktoberfest-dashboard
> react-scripts start

sh: react-scripts: command not found

npm ERR! Darwin 18.7.0
npm ERR! argv "node" "/Users/talaniz/.nvm/v0.10.32/bin/npm" "start"
npm ERR! node v0.10.32
npm ERR! npm  v2.14.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! hacktoberfest-monitor2@0.1.0 start: `react-scripts start`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the hacktoberfest-monitor2@0.1.0 start script 'react-scripts start'.
npm ERR! This is most likely a problem with the hacktoberfest-monitor2 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     react-scripts start
npm ERR! You can get their info via:
npm ERR!     npm owner ls hacktoberfest-monitor2
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/talaniz/Workspace/hacktoberfest-dashboard/npm-debug.log
```

**npm-debug.log**
```
0 info it worked if it ends with ok
1 verbose cli [ 'node', '/Users/talaniz/.nvm/v0.10.32/bin/npm', 'run', 'build' ]
2 info using npm@2.14.2
3 info using node@v0.10.32
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info prebuild hacktoberfest-monitor2@0.1.0
6 info build hacktoberfest-monitor2@0.1.0
7 verbose unsafe-perm in lifecycle true
8 info hacktoberfest-monitor2@0.1.0 Failed to exec build script
9 verbose stack Error: hacktoberfest-monitor2@0.1.0 build: `react-scripts build && cp ./build/index.html ./build/404.html`
9 verbose stack spawn ENOENT
9 verbose stack     at ChildProcess.<anonymous> (/Users/talaniz/.nvm/v0.10.32/lib/node_modules/npm/lib/utils/spawn.js:17:16)
9 verbose stack     at ChildProcess.emit (events.js:98:17)
9 verbose stack     at maybeClose (child_process.js:756:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:823:5)
10 verbose pkgid hacktoberfest-monitor2@0.1.0
11 verbose cwd /Users/talaniz/Workspace/hacktoberfest-dashboard
12 error Darwin 18.7.0
13 error argv "node" "/Users/talaniz/.nvm/v0.10.32/bin/npm" "run" "build"
14 error node v0.10.32
15 error npm  v2.14.2
16 error file sh
17 error code ELIFECYCLE
18 error errno ENOENT
19 error syscall spawn
20 error hacktoberfest-monitor2@0.1.0 build: `react-scripts build && cp ./build/index.html ./build/404.html`
20 error spawn ENOENT
21 error Failed at the hacktoberfest-monitor2@0.1.0 build script 'react-scripts build && cp ./build/index.html ./build/404.html'.
21 error This is most likely a problem with the hacktoberfest-monitor2 package,
21 error not with npm itself.
21 error Tell the author that this fails on your system:
21 error     react-scripts build && cp ./build/index.html ./build/404.html
```

**Comment by bgalek** [comment]
Hi!,
run `npm install` to download the dependencies, then it should work - if so, I'll update readme ;)

**Comment by talaniz** [comment]
Thanks, I managed to install the dependencies, I think there might be an issue with one of them, the react-scripts.js file looks like it's throwing some kind of unexpected syntax error (I'm not too familiar with js)--

```
 npm start                                                                                                                        ✔

> hacktoberfest-monitor2@0.1.0 start /Users/talaniz/Workspace/hacktoberfest-dashboard
> react-scripts start


/Users/talaniz/Workspace/hacktoberfest-dashboard/node_modules/react-scripts/bin/react-scripts.js:14
process.on('unhandledRejection', err => {
                                      ^
SyntaxError: Unexpected token >
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3

npm ERR! Darwin 18.7.0
npm ERR! argv "node" "/Users/talaniz/.nvm/v0.10.32/bin/npm" "start"
npm ERR! node v0.10.32
npm ERR! npm  v2.14.2
npm ERR! code ELIFECYCLE
npm ERR! hacktoberfest-monitor2@0.1.0 start: `react-scripts start`
npm ERR! Exit status 8
npm ERR!
npm ERR! Failed at the hacktoberfest-monitor2@0.1.0 start script 'react-scripts start'.
npm ERR! This is most likely a problem with the hacktoberfest-monitor2 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     react-scripts start
npm ERR! You can get their info via:
npm ERR!     npm owner ls hacktoberfest-monitor2
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/talaniz/Workspace/hacktoberfest-dashboard/npm-debug.log
```

**Comment by bgalek** [comment]
You need to upgrade your node, you're using an very outdated version :) use
LTS 12.0 or latest 13 branch,and you'll be ready to go :)

wt., 12 lis 2019, 18:56 użytkownik Antonio Alaniz <notifications@github.com>
napisał:

**Comment by osmarpetry** [comment]
Hello @talaniz, 
I tried the command here, and it worked. Try to do the same in a different machine in the same network with the latest nodejs, if it happened again the problem is on the network.

**Comment by bgalek** [comment]
project rewritten ;)
